-- 대장균 개체의 ID(ID)와 자식의 수(CHILD_COUNT)를 출력
-- 자식이 없다면 자식의 수는 0으로 출력
-- 개체의 ID 에 대해 오름차순 정렬

SELECT PARENT.ID, COUNT(CHILD.ID) AS CHILD_COUNT
FROM ECOLI_DATA PARENT 
LEFT JOIN ECOLI_DATA CHILD
ON PARENT.ID = CHILD.PARENT_ID
GROUP BY PARENT.ID
ORDER BY PARENT.ID