

#대여횟수가 5이상이 자동차 리스트
WITH checking AS (
    SELECT CAR_ID, COUNT(*)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)

#해당기간 동안의 월별 자동차id 별 총 대여횟수 조회
SELECT MONTH(START_DATE) MONTH, CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID FROM checking)
AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31' #해당기간 조건
GROUP BY MONTH, CAR_ID
HAVING RECORDS <> 0
ORDER BY MONTH ASC, CAR_ID DESC